dist: xenial

language: python

python:
  - "3.7-dev"

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
#  - pwd
#  - cd ~/; git clone https://github.com/amrex-codes/amrex
#  - cd ~/; git clone https://github.com/amrex-codes/regression_testing


addons:
   apt:
      packages:
      - g++
      - gfortran
      - pandoc
      - doxygen
      - libgmp-dev
      - libmpfr-dev
      - pandoc
      - doxygen
      - texlive
      - texlive-latex-extra
      - texlive-lang-cjk
      - latexmk
      - mpich
      - libmpich-dev

install:
  - pip install -r requirements.txt

script: bash ./build_and_deploy.sh

env:
  global:
  - COMMIT_AUTHOR_EMAIL: "jmsexton@lbl.gov"