name: Build and Deploy

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install -r ./requirements.txt

      - name: Dependencies
        run: |
          .github/workflows/dependencies/documentation.sh
          python3 -m pip install sphinx sphinx_rtd_theme breathe sphinxcontrib_bibtex numpydoc more_itertools nbsphinx ipython

      - name: Install and Build
        run: |
          ./build_docs.sh

      - name: Deploy
        if: github.event_name == 'push' &&
            github.repository == 'AMReX-Astro/Nyx' &&
            github.ref == 'refs/heads/development'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: false
          token: ${{ secrets.GITHUB_TOKEN }}
